language: ruby

rvm:
 - 2.6.0

services:
 - postgresql

env:
 - DATABASE_URL=postgresql://quasars_test@postgres:5432/quasars?encoding=utf8&pool=5&timeout=5000

before_script:
 - psql -c 'create database quasars_test;' -U postgres
