language: ruby

rvm:
 - 2.6.0

services:
 - postgresql
 - docker

env:
 - DATABASE_URL=postgresql://quasars_test@postgres:5432/quasars?encoding=utf8&pool=5&timeout=5000

before_script:
 - psql -c 'create database quasars_test;' -U postgres
 - bin/rails db:migrate RAILS_ENV=test

deploy:
  provider: script
  script: bash docker_push.sh
  # TODO: Remove comments
  # on:
    # branch: master