language: generic

services:
 - docker

before_script:
 - docker-compose build
 - docker-compose run quasars bin/rails db:migrate RAILS_ENV=test

script:
 - docker-compose run quasars rake

deploy:
  provider: script
  script:
   - bash docker_push.sh
  # TODO: Change to master
  on:
    branch: docker