version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    build: .
    command: bundle exec puma -t 5:5 -p ${PORT:-3000} -e ${RAILS_ENV:-development}
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db