version: '3'
services:
  db:
    image: postgres
    volumes:
      - postgres-volume:/var/lib/postgresql/data
  web:
    build: .
    command: bundle exec puma -C config/puma.rb
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  postgres-volume:
    external: true