version: '3'

volumes:
  postgres_data: {}

services:
  postgres:
    image: postgres:10.6
    environment:
      POSTGRES_USER: quasars
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    depends_on:
      - quasars
    ports:
      - 80:80

  quasars:
    build: .
    depends_on:
      - postgres
    volumes:
      - /var/www/quasars
    env_file:
      - .quasars.env
